Loaded dependency [python3/3.11.4]: gcc/12.3.0-binutils-2.40
Loaded dependency [python3/3.11.4]: sqlite3/3.42.0
Loaded module: python3/3.11.4

Loading python3/3.11.4
  Loading requirement: gcc/12.3.0-binutils-2.40 sqlite3/3.42.0
Loaded dependency [numpy/1.24.3-python-3.11.4-openblas-0.3.23]: openblas/0.3.23
Loaded dependency [pandas/2.0.2-python-3.11.4]: numpy/1.24.3-python-3.11.4-openblas-0.3.23
Loaded module: pandas/2.0.2-python-3.11.4

Loading pandas/2.0.2-python-3.11.4
  Loading requirement: openblas/0.3.23
    numpy/1.24.3-python-3.11.4-openblas-0.3.23
Loaded dependency [matplotlib/3.7.1-numpy-1.24.3-python-3.11.4]: scipy/1.10.1-python-3.11.4
Loaded module: matplotlib/3.7.1-numpy-1.24.3-python-3.11.4

Loading matplotlib/3.7.1-numpy-1.24.3-python-3.11.4
  Loading requirement: scipy/1.10.1-python-3.11.4
Traceback (most recent call last):
  File "/zhome/ec/4/183935/Prediction-of-protein-isoforms-using-semi-supervised-learning/pca.py", line 42, in <module>
    plot(Z[:,0],Z[:,1], format="b.")
  File "/appl/matplotlib/3.7.1-numpy-1.24.3-python-3.11.4/lib/python3.11/site-packages/matplotlib/pyplot.py", line 2812, in plot
    return gca().plot(
           ^^^^^^^^^^^
  File "/appl/matplotlib/3.7.1-numpy-1.24.3-python-3.11.4/lib/python3.11/site-packages/matplotlib/axes/_axes.py", line 1688, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/appl/matplotlib/3.7.1-numpy-1.24.3-python-3.11.4/lib/python3.11/site-packages/matplotlib/axes/_base.py", line 311, in __call__
    yield from self._plot_args(
               ^^^^^^^^^^^^^^^^
  File "/appl/matplotlib/3.7.1-numpy-1.24.3-python-3.11.4/lib/python3.11/site-packages/matplotlib/axes/_base.py", line 544, in _plot_args
    return [l[0] for l in result]
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/appl/matplotlib/3.7.1-numpy-1.24.3-python-3.11.4/lib/python3.11/site-packages/matplotlib/axes/_base.py", line 544, in <listcomp>
    return [l[0] for l in result]
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/appl/matplotlib/3.7.1-numpy-1.24.3-python-3.11.4/lib/python3.11/site-packages/matplotlib/axes/_base.py", line 537, in <genexpr>
    result = (make_artist(x[:, j % ncx], y[:, j % ncy], kw,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/appl/matplotlib/3.7.1-numpy-1.24.3-python-3.11.4/lib/python3.11/site-packages/matplotlib/axes/_base.py", line 351, in _makeline
    seg = mlines.Line2D(x, y, **kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/appl/matplotlib/3.7.1-numpy-1.24.3-python-3.11.4/lib/python3.11/site-packages/matplotlib/_api/deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/appl/matplotlib/3.7.1-numpy-1.24.3-python-3.11.4/lib/python3.11/site-packages/matplotlib/lines.py", line 393, in __init__
    self._internal_update(kwargs)
  File "/appl/matplotlib/3.7.1-numpy-1.24.3-python-3.11.4/lib/python3.11/site-packages/matplotlib/artist.py", line 1223, in _internal_update
    return self._update_props(
           ^^^^^^^^^^^^^^^^^^^
  File "/appl/matplotlib/3.7.1-numpy-1.24.3-python-3.11.4/lib/python3.11/site-packages/matplotlib/artist.py", line 1197, in _update_props
    raise AttributeError(
AttributeError: Line2D.set() got an unexpected keyword argument 'format'
